<div class="container">
    <div class="d-flex justify-content-center mt-5 py-5">
        <form class="shadow-lg p-5" action="index.php" method="POST">
            <h4 class="text-center">Add User</h4>
            <div class="mb-2">
                <input type="text" placeholder="Nom" name="nom" class="form-control" value="<?=$nom?>">
                <small class="text-danger"><?= array_key_exists("nom", $errors) ? $errors['nom'] : '' ?></small>
            </div>
            <div class="mb-2">
                <input type="text" placeholder="prenom" name="prenom" class="form-control" value="<?=$prenom?>">
                <small class="text-danger"><?= array_key_exists("prenom", $errors) ? $errors['prenom'] : '' ?></small>
            </div>
            <div class="mb-2">
                <input type="email" placeholder="Email" name="email" class="form-control" value="<?=$email?>">
                <small class="text-danger"><?= array_key_exists("email", $errors) ? $errors['email'] : '' ?></small>
            </div>
            <div class="mb-2">
                <input type="password" placeholder="Password" name="password" class="form-control" value="<?=$password?>">
                <small class="text-danger"><?= array_key_exists("password", $errors) ? $errors['password'] : '' ?></small>
            </div>
            <div class="mb-2 text-center">
                <button type="submit" name="submit" class="btn btn-outline-success">Add</button>
            </div>
        </form>
    </div>
</div>