<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="icon" href="./assets/images/boycott.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title><?= $page_titel; ?></title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: whitesmoke;
        }

        .preloader {
            background-color: whitesmoke;
            height: 100vh;
            z-index: 99999;
            position: fixed;

            top: 0;
            left: 0;
            width: 100vw;
            display: flex;
            justify-content: center;
            align-items: center
        }

        .preloader.enter_pre {
            display: none;
        }

        .preloader img {
            width: 200px;
            height: 200px;
            animation: animate 4s infinite;
        }

        @keyframes animate {
            0% {
                transform: scale(0);
            }

            100% {
                transform: scale(50px)
            }
        }

        .logo {
            width: 50px;
            height: 50px;
        }

        .navbar.sticky {
            padding: 10px;
            box-shadow: 0px 2px 20px rgba(1, 41, 112, 0.1);
            transition: 0.5s;
        }

        .section {
            height: 100vh;
            width: 100%;
            background-image: url('./assets/images/tunisia_palestine.jpg');
            background-repeat: no-repeat;
            background-position: center;
            overflow: hidden;
            position: relative;
            background-size: cover;
        }

        .text {
            background: transparent;
            position: absolute;
            top: 50%;
            color: #fff;
            font-size: 25px;
            font-weight: bold;
            left: 50%;
            text-align: center;
            transform: translate(-50%, -50%);
        }

        p {
            background: transparent;
        }
    </style>
</head>
<script>
    function loader() {
        document.querySelector('.preloader').classList.add("enter_pre");
    }

    function fadeout() {
        setInterval(loader, 1);
    }

    window.onload = fadeout();

    window.addEventListener('scroll', function() {
        const header = document.querySelector('.navbar');
        header.classList.toggle('sticky', window.scrollY > 20);
    });
</script>

<body>
    <div class="preloader">
        <div class="content-preloader">
            <img src="./assets/images/boycott.png" alt="boycott">
        </div>
    </div>
    <nav class="navbar fixed-top">
        <div class="container">
        <?php if (empty($template)) : ?>
            <img src="./assets/images/boycott.png" class="logo" alt="boycott">
        <?php else :?>
            <img src="../assets/images/boycott.png" class="logo" alt="boycott">
         <?php endif ?>
          <div class="d-flex">
                <button class="btn btn-outline-secondary">Login</button>
           </div>
        </div>
    </nav>
    <?php if (empty($template)) : ?>

        <div>
            <div class="section">
                <div class="text">
                    <p>Support Palestine. Boycott Israel
                    </p>
                    <p> Stand with the Palestinians in their struggle for freedom, justice, and equality. Whilst our governments financially support the apartheid state, we don't have to.</p>
                    <a href="./ListCategory/">
                        <button class="btn btn-dark">
                            Browse Category
                        </button>
                    </a>
                </div>
            </div>
            <div class="container">
                <footer class="d-flex flex-wrap justify-content-between align-items-center my-4 border-top">
                    <div class="col-md-12 d-flex  justify-content-center align-items-center">
                        <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Boycott, Inc</span>
                    </div>
                </footer>
            </div>
        </div>
    <?php else : ?>
        <?php include $template . '.phtml' ?>
    <?php endif; ?>
</body>

<script src="./assets/js/main.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</html>