<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <link rel="icon" href="./assets/images/boycott.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title><?= $page_titel; ?></title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .preloader {
            background-color: whitesmoke;
            height: 100vh;
            z-index: 99999;
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            display: flex;
            justify-content: center;
            align-items: center
        }

        .preloader.enter_pre {
            display: none;
        }

        img {
            width: 200px;
            height: 200px;
            animation: animate 4s infinite;
        }

        @keyframes animate {
            0% {
                transform: scale(0);
            }

            100% {
                transform: scale(50px)
            }
        }
    </style>
</head>
<script>

function loader() {
    document.querySelector('.preloader').classList.add("enter_pre");
}

function fadeout() {
    setInterval(loader, 4000);
}

window.onload = fadeout();
</script>
<body>
    <?php if (empty($template)) : ?>
        <div class="preloader">
            <div class="content-preloader">
                <img src="./assets/images/boycott.png" alt="boycott">
            </div>
        </div>
        <div>
            hello user
        </div>
    <?php else : ?>
        <?php include $template . '.phtml' ?>
    <?php endif; ?>
</body>

<script src="./assets/js/main.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</html>