<div class="container d-flex justify-content-center mt-5 py-5 align-items-center">
    <div class="col-md-5">
        <div class="card">
                <div class="alert alert-danger">
                    <?=$errors[0];?>
                </div>
                <a href="../signup/">
                    <button class="btn btn-outline-success">Go Back</button>
                </a>
        </div>
    </div>
</div>